# Generated by Django 3.2.9 on 2021-11-27 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zipcode',
        ),
    ]
