# Generated by Django 3.2.9 on 2021-11-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_delete_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
    ]
