# Generated by Django 3.2.9 on 2021-12-05 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_company_joblevel_jobpost_jobtype_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
